### PR TITLE
New PHProjekt Style

### PR DESCRIPTION
**Pull request by dsp**

### CODE REVIEW

**Comment by exi** [comment]
there are still render bug for the breadcrumb.
style but

**Comment by dsp** [comment]
should make things better. After that change i wasnt able to reproduce it anymore

**Comment by voidus** [comment]
I can't find an interface for tags.
I'm not sure if we shouldn't seperate the project list somehow. But maybe I'm just too used to the old look.

**Comment by exi** [comment]
the tree leaves should use better/different handle images.
specifically the last image in "css/themes/phprojekt/images/spriteTree.gif" should use some kind of box or at least a small line to the top.
The current image leads to some weird renderings on mouseover too, because the box in front of the project is disappearing on mouseover:
Alt text

**Comment by dsp** [comment]
well i wont have time to fix ithis till the release. so we either merge there branch as it is  or wait for perfection

**Comment by dsp** [comment]
@voidus tags will be searchable with a follow up branch

**Comment by exi** [comment]
ok, i'll merge it later and assign a followup ticket to you

**Comment by exi** [comment]
please add the following patch to the pull request, this fixes the mouseover bug. Then i will merge it.

http://dump.wthack.de/p6.patch

**Comment by dsp** [comment]
do ne

**Pull request merged**
