### PR TITLE
Phprojekt 361 Tags

### PR DESCRIPTION
**Pull request by exi**
Add the tags/search rewrite.
The calendar tests will fail with this branch because they are actually broken and the new test db dump triggers this as the older one was invalid

### CODE REVIEW

**Comment by exi** [comment]
rebased to remove unnecessary groups code.
Tests might fail because of actual errors that did not get triggered because the test database in next is invalid.
Some of the tests failures will be fixed in the following pull request.
I will not repair the failing tests here as they have nothing to do with the test code and are already broken in next.
This is a separate issue.

**Comment by voidus** [comment]
The travis build did actually not succeed. It's broken by a bug that is fixed in the current next. Please merge it into this branch.

**Comment by exi** [comment]
travis build fails, but its a valid calendar issue, no problem with the tags code

**Comment by exi** [comment]
build still fails, but this is still not tags related :)

**Comment by voidus** [comment]
The cause of the broken tests is fixed in https://github.com/Mayflower/PHProjekt/pull/288, although you could have fixed this just as easily as I did. Just saying.

**Pull request merged**
