### PR TITLE
Fix the server-chokes-on-list-view thing

### PR DESCRIPTION
**Pull request by voidus**
count should be merged before this.

This implements a Rest Controller, deprecates the old grid, alters a copy so that it uses the new controller and implements all this for the calendar and todo.

http://jira.opensource.mayflower.de/jira/browse/PHPROJEKT-341

### CODE REVIEW

**Comment by exi** [comment]
use Zend_Json::decode() and Zend_Json::encode() instead of Zend_Json_Decoder::decode() and Zend_Json_Encoder::encode()
Zend_Json::decode decides at runtime whether to use the php buildin or a php implementation.
Zend_Json_Decoder will always be slower and will be used as the fallback implementation by Zend_Json::decode

**Comment by dsp** [comment]
using this branch "todo" doesnt display anything anymore. looking into that in the next days.

**Comment by dsp** [comment]
I would recommend not merging this into next before 6.1.0 final release. it's a little bit too much for the final 6.1.0 release

**Comment by voidus** [comment]
As this fixes http://jira.opensource.mayflower.de/jira/browse/PHPROJEKT-341, we can't really not merge this.

**Comment by voidus** [comment]
I'm not really sure if it's wise to fall back to project id 1. What do you think?

**Comment by exi** [comment]
superseeded by a new pull request

**Pull request closed without merging**
